#
# 注意：对于字符串应该使用单引号
# path, host, schemes, methods, defaults, requirements
#
post-tickets:
    path: /tickets
    defaults: {_controller: 'TicketController::staffCreateTicket'}
    methods: ['POST']

get-tickets:
    path: /tickets/{id}
    defaults: {_controller: 'TicketController::getTicketList'}
    requirements: {id: '\d+'}
    methods: ['GET']

